Development
hitcherland/FoundryVTT-Heart pull request #29
Opened 2022-06-05 23:11 UTC by stuttste

Fleshed out Haunts and Landmarks in this one. Decided to hold off on Delves for now since our session 1 is tomorrow and I don't wanna accidentally break something before then. lol

Noticed you pushed 0.4.7, so merged and changed mine to 0.4.8

2022-06-05 23:20 UTC, stuttste commented
Left out Default Stress on the Landmarks. I'll create an issue on it so we don't forget.

2022-06-06 10:38 UTC, hitcherland commented on src/items/haunt/template.json
> +            "die_sizes": ["d4", "d6", "d8", "d10", "d12"],
We don't need to add die_sizes to an item template; these templates are for per-item properties and die sizes are global.

2022-06-06 10:41 UTC, hitcherland commented on src/items/haunt/sheet.js
> +            const dieSizes = this.item.data.data.die_sizes;
This should use `game.heart.die_sizes` instead.

2022-06-06 10:41 UTC, hitcherland commented on src/items/haunt/sheet.js
> +            const dieSizes = this.item.data.data.die_sizes;
This should use `game.heart.die_sizes` instead.

2022-06-06 10:45 UTC, hitcherland commented on src/items/haunt/lang/en.json
> +    "service": {
If we're keeping services, this belongs in the "service/lang/{xx}.json" files

2022-06-06 10:46 UTC, hitcherland commented on src/items/haunt/lang/es.json
> +    "service": {
As above, this would belong in service/lang/es.json

2022-06-06 10:50 UTC, hitcherland commented on src/items/haunt/preview.html
> +    <div class="section {{localizeHeart service 'label-multiple'}}">
We don't need the distinct item "service" here to represent different resistance rolls, that capability should be directly added to Haunts.

2022-06-06 10:53 UTC, hitcherland commented on src/items/haunt/template.json
> +            "templates": ["has_description", "has_children", "is_activatable"],
As discussed elsewhere, haunts shouldn't need children.

2022-06-06 10:55 UTC, hitcherland commented on src/items/haunt/template.json
>          }
Let's add a `resistances: []` section here, which should replace the need for the `services` item.

2022-06-06 16:07 UTC, stuttste commented on src/items/haunt/template.json
> +            "die_sizes": ["d4", "d6", "d8", "d10", "d12"],
I should be able to get this removed. Had trouble getting to the original die_sizes parameter but the below should give me what I need there I think.

2022-06-06 16:08 UTC, stuttste commented on src/items/haunt/sheet.js
> +            const dieSizes = this.item.data.data.die_sizes;
Got it. I should be able to swap to that.

2022-06-06 16:08 UTC, stuttste commented on src/items/haunt/sheet.js
> +            const dieSizes = this.item.data.data.die_sizes;
As above

2022-06-06 16:09 UTC, stuttste commented on src/items/haunt/lang/en.json
> +    "service": {
Makes sense. Think this was leftover from my initial attempts to keep it all contained within haunts. Will correct once we settle which path we wanna take.

2022-06-06 16:09 UTC, stuttste commented on src/items/haunt/lang/es.json
> +    "service": {
As above

2022-06-06 18:55 UTC, stuttste commented
For the life of me, though, I cannot get selectOptions to work correctly for the Haunt object. It seems to be related to me extending the base object, but I can't figure out what I'm doing differently to cause the options list to be undefined. Attempting to just plug and play the `{{selectOptions die_sizes selected=<resistances array>}}` just will not work.

2022-06-07 19:03 UTC, stuttste commented
![image](https://user-images.githubusercontent.com/10578770/172461645-d0fb3a86-80d3-4a7e-8ff9-8ad2c402537a.png)

This is the result if we decide to omit the service-level object. Is this the path we want to take? (Ignore the middle "Services" section.)

2022-06-09 19:56 UTC, stuttste commented
Perfect. Yep, I'll be sure that's in there as well. Wanted to clear the format with you before continuing. Thanks. Will get another commit posted soonish.

2022-06-10 16:23 UTC, stuttste commented
Ok, committed and reviewed. I think I got everything we mentioned.

2022-06-11 08:09 UTC, hitcherland commented on release-notes/v0.4.8/lang/en.json
> +                "Created 'Service' item type to represent services rendered by haunts; EDIT: Service object removed in favor of internal array/object of Haunts.",
Users won't knowthe context for this EDIT, please remove.

2022-06-11 08:12 UTC, hitcherland commented on src/items/haunt/sheet.js
> +                flavor: `${localizeHeart(this.item.name)} (<span class="item-type">${this.item.type}</span>)`,
We should include the resistance type in the roll output, i.e. add `localizeHeart(service.resistance)` in there somewhere

2022-06-11 08:18 UTC, hitcherland requested changes
This is just about ready to be submitted! I noticed some problems dragging Haunts out of Landmarks and into the items tab, but I didn't have time to check if that was a general problem or not, so it can wait for a future release.

2022-06-11 16:41 UTC, stuttste commented
Great! Changes made. Yeah, drag-n-drop is something I wanted to look into at some point too. Mainly, seems like dragging and dropping resources from adversary to characters didn't seem to work when I tried it. Would be a convenient thing to have when DM'ing. Also a 'share'/'send' button for players to give resources to one another.

2022-06-12 16:13 UTC, stuttste commented
You're absolutely right. I hadn't even considered that. Thanks! Should be updated now.

2022-06-12 21:05 UTC, merged